### ISSUE TITLE
Proposal: excluded hosts inventory file

### ISSUE THREAD

**Issue by aweiteka** [openshift/openshift-tools#2975]
## Problem

We need a way to filter which hosts or clusters ansible runs against. We need to be able to easily update these exceptions, track and control changes, and display excluded hosts in TBD tools.

## Proposal

Create a flexible data structure that expresses excluded hosts. Extend `ansible/inventory/multi_inventory.py` script to apply excluded host filter.

## Justification

Using the kubernetes API as a model the flat list of items of different 'kinds' allows us to arbitrarily add excluded hosts rules. The downside of this approach is the difficulty of figuring out what the exception schedule is for a particular account. Another downside is the difficulty in understanding what a complex set of maintenance windows might impact a rollout.

**Questions:**

- How would we differentiate between ansible runs to identify maintenance vs config loop vs upgrade?
- How would we express daily windows that extend into another day? Multiple windows should work.

### Data format example `excluded_hosts.yaml`

```yaml
---
- kind: no_maintenance
  description: Daily NASA blackout maintenance window
  match:
    type: oo_clusterid
    items:
      - companyb
      - acme
  windows:
    - range:
        - "10:00Z"
        - "23:59Z"
- kind: no_maintenance
  description: Multi-day EMEA blackout maintenance window
  match:
    type: oo_clusterid
    items:
      - tech1
  windows:
    - range:
        - "2017-12-018T01:00Z"
        - "2018-01-03T22:00Z"
- kind: no_configloop
  description: Quarantine broken hosts
  match:
    type: oo_name
    items:
      - opstest-ip-172-89-51-231.ec2.internal
- kind: no_upgrade
  description: Upgrade blacklist
  match:
    type: oo_clusterid
    items:
      - fusion8
      - brand1
      - cm-ops
      - dev-preview
      - devops
      - openshift-stage
      - openshiftops
```

### Implementation

**Configuration**

New item in `multi_inventory.yaml`:

```
excluded_hosts_location: /path/to/excluded_hosts.yaml
```

**UX**

Output all hosts inventory (current implementation)

    ansible/inventory/multi_inventory.py 

Output inventory with excluded hosts removed using current time

    ansible/inventory/multi_inventory.py --exclude-hosts

Output inventory without excluded hosts, override time

    ansible/inventory/multi_inventory.py --exclude-hosts --time '2017-10-31T12:00:00Z'

Output just excluded hosts to answer question "Which hosts would be excluded now from inventory?"

    ansible/inventory/multi_inventory.py --excluded-hosts-only

### How to get there

1. Extend `ansible/inventory/multi_inventory.py --exclude-hosts=False` (default) and [associated tests](https://github.com/openshift/openshift-tools/blob/prod/test/units/multi_inventory_test.py)
1. Develop excluded hosts validation test so we can safely change `excluded_hosts.yaml`
1. Consider dynamic inventory logging so excluded_hosts can be monitored and audited
